<!DOCTYPE html> <!-- auto complete ctrl+espaço-->
<html lang ="pt-br">
<head>
	<meta charset="utf-8">
	<title>Pagina Inicial</title>
</head>
<body>
<!-- formatando em HTML-->
	<h1>EMANUELLY CHRISTYNE</h1>
	<p> <big><b>VOCÊ É LINDAAA!!!!!!!!!!!</b></big> </p>
	

	<p align="center"><b>lindaaaaaaaaaaaaaa</b></p>

	

	<?php//programação em php
		//declaração variavel
	$nome = "EMANUELLY";
	$idade = 15;

		//Mostra na tela as variaveis:

		echo"Meu nome é " .$nome." e tenho ". $idade. " anos";


	?>

</body>
</html>